<p>
	In the age of affordable smart phones, Bluetooth enabled personal area networks, portable devices with ubiquitous Internet access, cloud computing for convenient access to files and vast storage from anywhere, smart environments enabled by things like cheap customizable sensor technology and RFID tagging, there are many innovative opportunities to provide users, including especially those who experience disabilities, with greater mobility, autonomy and independence. At the heart of this research are the complimentary goals of providing (a) the ability to access services and information in a variety of settings, activities and environments and (b) the ability to transform these environments and tools to reduce disability brought on by a mismatch with the needs of the individual. These two goals entail theoretical and applied research into four related areas: Context-aware Services and Cognition, Smart Interfaces, Participatory Material Culture, and Adaptive Games and Inclusive Play.  
</p>

<h3>Area # 1: Context-aware Services and Cognition</h3>
<p>
Context-aware services are of particular importance to those with cognitive disabilities and/or neurological impairments that affect communication. Persons diagnosed with aphasia, autism spectrum disorders, pervasive developmental disorders, and those with other mild intellectual disabilities are enabled by mobile devices with context-aware services that offer visual information as cues to improve their understanding of their spatial environment. In these research projects users, parents/caregivers, therapists, and teachers are actively engaged in the design of the services, data collection, analysis, and in developing feedback for redesign. It is this participatory action element that delivers tangible improvements to the development of services in timeframes that are acceptable to those who benefit most from these mobile systems.
</p>

<h3>Area #2: Smart Interfaces</h3>
<p>
The interfaces to information and information systems can be made more adaptable and customizable based on context. One avenue for exploring these challenges is via rapid prototyping of both hardware and software. Digital and material interfaces can now be quickly designed and constructed in non-industrial settings, by non-professionals, thus empowering individuals to modify or create entirely new interfaces and devices, while simultaneously exploring the material and environmental ramifications of their designs. This presents interesting research challenges in the areas of Human-Computer Interaction (HCI) and system design (for example, with respect to requirements engineering or the design of prototyping technologies themselves). 
</p>

<h3>Area #3: Participatory Material Culture</h3>
<p>
In keeping with increasing autonomy, mobile computing devices allow not only the retrieval of context-specific information, but also the active participation of users in the co-construction of information that is tied to particular places and objects and potentially shared across a community of users. Social tagging/bookmarking is already a common practice on the Web and, with mobile devices, is being extended to real places and objects. Rapid prototyping and “3-d printing” technologies, combined with a variety of smart cheap sensors, can be used in this area as well to empower individuals to personalize and customize their environments and thus reduce the “mismatch” with their own abilities that leads to the experience of disability.  Such solutions, as well as the design process, can be shared across open-source communities, but more research is needed into economically sustainable infrastructure models to facilitate this sharing as well as support the digitally-mediated, knowledge-sharing communities on which it rests.  
</p>

<h3>Area #4: Adaptive Games and Inclusive Play</h3>
<p>
There is growing evidence that digital games can fulfill a number of important functions in the lives of disabled children and adults. Games that draw upon geolocation data, physical movement and other non-traditional forms of user interaction are especially promising in this regard, as suggested by recent studies demonstrating how kinetic game systems such as the Nintendo Wii can facilitate entry into gaming for disabled players, both as a novel and entertaining leisure activity, as well as an innovative approach to rehabilitation and exercise. Ongoing developments within gaming technologies and design, such as the introduction of WYSIWYG tools for creating, modifying or heavily customizing games at the level of design, suggest additional opportunities for improving the lives of users with disabilities and other special needs. 
</p>
